title: midnightbard
titlerss: Midnight Bard
description: backup
descriptionrss: RSS
author: midnightbard
url: https://midnightbard.com

logo: /icons/rss.png
image: /icons/rss.png
imagerss: /icons/rss.png
locale: en_US

feed_items: 1000
feed_update_period: daily
feed_update_frequency: 1

layouts_dir: _layouts

collections:
  community:
    output: true
    permalink: /:title/
  technology:
    output: true
    permalink: /:title/

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      permalink: /:title/
  - scope:
      path: ""
      type: community
    values:
      layout: post
  - scope:
      path: ""
      type: technology
    values:
      layout: post

permalink: /:title/

markdown: kramdown
highlighter: rouge

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

exclude:
  - Gemfile
  - exclude/

future: false